### ISSUE TITLE
Add Dark Mode Support

### ISSUE THREAD

**Issue by DanielEskinazi** [DanielEskinazi/claude-agent-test#7]
We should add dark mode support to improve user experience and accessibility.

## Current Situation
- Website only has light mode
- Some users might prefer dark mode for reading
- No way to switch between themes

## Proposed Changes
1. Add CSS variables for colors
2. Create dark mode color palette
3. Add theme toggle button in navigation
4. Store user preference in localStorage

## Technical Requirements
```css
/* Example CSS Variables */
:root {
  --bg-color: #ffffff;
  --text-color: #333333;
  --primary-color: #2c3e50;
}

[data-theme="dark"] {
  --bg-color: #1a1a1a;
  --text-color: #ffffff;
  --primary-color: #3498db;
}
```

## Success Criteria
- [ ] Dark mode toggle works
- [ ] All content remains readable
- [ ] User preference persists between visits
- [ ] Smooth transition between modes
- [ ] Respects system preference by default

## Questions
- Should we add an auto-detect feature for system preferences?
- What should be the default theme?
- Should we add a keyboard shortcut for toggling?

/cc @DanielEskinazi
